# Generated by Django 5.0.3 on 2024-03-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytracksrequest',
            old_name='track_data',
            new_name='tracks_data',
        ),
    ]
